#
# This pipeline needs the following tasks from Tekton Hub:
#   - git-clone
#   - flake8
#   - nose
#   - buildah
#   - openshift-client
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      description: URL of the Git repository
    - name: branch
      description: Git branch to clone
      default: main
    - name: build-image
      description: Image name to build and push (e.g. image-registry.openshift-image-registry.svc:5000/namespace/accounts:latest)
    - name: deploy-manifest
      description: Path to the Kubernetes deployment YAML
      default: deploy/deployment.yaml

  tasks:
    # Clean up workspace
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    # Clone repository
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    # Linting step
    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: python:3.9-slim
        - name: args
          value:
            - --count
            - --max-complexity=10
            - --max-line-length=127
            - --statistics

    # Testing step
    - name: tests
      runAfter:
        - clone
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"

    # Build container image using Buildah
    - name: build
      runAfter:
        - lint
        - tests
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.build-image)

    # Deploy to OpenShift using openshift-client
    - name: deploy
      runAfter:
        - build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
      params:
        - name: SCRIPT
          value: |
            echo "Updating manifest..."
            sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
            cat deploy/deployment.yaml
            echo "Deploying to OpenShift..."
            oc apply -f deploy/
            oc get pods -l app=accounts
